version: "3.8"
services:
  database:
    container_name: pg_test_db
    image: postgres:15-alpine
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 6432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_test_db
    ports:
      - 6432:5432
    volumes:
      - pg-demo-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_demo_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: scott.a.shannon@outlook.com
      PGADMIN_DEFAULT_PASSWORD: docker
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
   
volumes:
  pg-demo-data:
  pgadmin-data: